{% set version = "22.13.0" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 127 %}

package:
  name: nodejs
  version: {{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [unix]
  sha256: 38e15a1d0dd0e95c237bc4651d7c9930a78d3fe7954a7ee7693b403f2d879e46  # [unix]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [target_platform == "win-64"]
  sha256: b0feb09ebf41328628e7383f7a092fb7342ce1e05c867a90cf8f1379205a8429  # [target_platform == "win-64"]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-arm64.zip  # [target_platform == "win-arm64"]
  sha256: 8ca2c90ae0373d69e13301293306c31ea9afca2780b8325b6ca059319479e560  # [target_platform == "win-arm64"]
  patches:
    - patches/0001-stop-removing-librt.patch  # [not win]
    - patches/0002-include-obj-name-in-shared-intermediate.patch  # [not win]
    - patches/0003-Forward-ceilf-floorf.patch  # [not win]

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}      # [not win]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.8  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]

    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv

    # need host builds of several lib dependencies
    # when cross-compiling
    - icu  # [build_platform != target_platform]
    - openssl  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
  host:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
