{% set version = "11.10.1" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 1652c919cb56e264fb7e0b00c4d038766af943ed3db94865cbeb01360175777b  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: 80cf14abacbc6b636bc192f4eee49421f082f21cdaa9c1ea5995c38f8c1375e5  # [win]
  patches:
    - macosx-target.patch  # [not win]

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 2.7.*  # [not win]
  host:
    - vs2015_runtime  # [win]
  run:
    - vs2015_runtime  # [win]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
