{% set version = "16.20.2" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 93 %}

package:
  name: nodejs
  version: {{ version }}

source:
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 33188eb11b977113adb65b2e09d71bddd63f12168ba73ceadae6c27938dc9e93  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: f8bb35f6c08dc7bf14ac753509c06ed1a7ebf5b390cd3fbdc8f8c1aedd020ec3  # [win]
  patches:
    - 0001-stop-removing-librt.patch  # [not win]
    - 0002-Use-cinttypes-header.patch  # [linux]
    - 0003-include-obj-name-in-shared-intermediate.patch  # [not win]
    - 0004-Forward-ceilf-floorf.patch  # [not win]
    - 0005-Force-include-handler-outside-simulator.patch  # [osx and arm64]
    - 0006-trap-handler-doesn-t-work-on-linux-cross-compile-to-.patch  # [linux and aarch64]
    - 0007-Remove-usage-of-msign-return-address-all.patch  # [linux and aarch64]

build:
  number: 3
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.8  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]

    # need host builds of several lib dependencies
    # when cross-compiling
    - icu  # [build_platform != target_platform]
    - libuv  # [build_platform != target_platform]
    - openssl  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
  host:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
