{% set version = "9.9.0" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz
  sha256: e774cf32bc7c1d61d2e654e67eaafd2a13f22f176933706de60250db5b5eabda

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    # node's build scripts find and use MSVC 2015, regardless of conda's setting.
    - toolchain
    - vs2015_runtime  # [win]
    - python          2.7.*
    - gcc             # [linux]
  run:
    - vs2015_runtime   # [win]
    - libgcc           # [linux]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
