{% set version = "20.12.2" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 115 %}

package:
  name: nodejs
  version: {{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [unix]
  sha256: bc57ee721a12cc8be55bb90b4a9a2f598aed5581d5199ec3bd171a4781bfecda  # [unix]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: 66dda1717cae30a13be6bb17ad96ee54b69f2c23c85acd9c3299b095fa26b452  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]
    - less-shared-intermediate.patch  # [not win]
    - 0001-Forward-ceilf-floorf.patch  # [not win]
    - 0001-Disable-unsupported-branch-protection.patch  # [not win]

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
    - python 3.8  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]

    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv

    # need host builds of several lib dependencies
    # when cross-compiling
    - icu  # [build_platform != target_platform]
    - openssl  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
  host:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
