{% set version = "12.22.6" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 02763dcf6532a997143b03c1f7d23552a3bd19ddcad1fd2425956db7596cbc9c  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: d35a21d6d7b517c6bf4132abfbbdd447dfe46f5e1de3194d5f4152395a1ac6a2  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]

build:
  number: 1
  ignore_prefix_files:
    - bin/node
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 2.7  # [not win]
    - git  # [linux]
    - make  # [linux]
    - pkg-config  # [not win]
  host:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv >=1.34  # [not win]
    - openssl >=1.1.1d   # [not win]
    - zlib  # [not win]
  run:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv  # [not win]
    - openssl >=1.1.1d  # [not win]
    - zlib  # [not win]
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - roccqqck
    - xhochy
