{% set version = "12.16.3" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 4694056576b6c48a70ad401cf061181eafbc3cbf5070907cdba4e6de1be567a5  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: d0bb0e0b1f1a948529ddd543e2cfe0bfe209eb843defc70217b3d2f84cbf3b78  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 2.7  # [not win]
    - git  # [linux]
    - make  # [linux]
    - pkg-config  # [not win]
  host:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv >=1.34  # [not win]
    - openssl >=1.1.1d   # [not win]
    - zlib  # [not win]
  run:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv  # [not win]
    - openssl >=1.1.1d  # [not win]
    - zlib  # [not win]
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
