schema_version: 1

context:
  version: 22.19.0
  # NODE_MODULE_VERSION set in src/node_version.h
  NODE_MODULE_VERSION: 127

package:
  name: nodejs
  version: ${{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  - if: unix
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}.tar.gz
      sha256: 4cea680423f98abc6a2a5ca127fb34c5f6586c24217f57749be6ea886c9be9a6
      patches:
        - patches/0001-stop-removing-librt.patch
        - patches/0002-include-obj-name-in-shared-intermediate.patch
        - patches/0003-Forward-ceilf-floorf.patch
  - if: target_platform == "win-64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-x64.zip
      sha256: ea3fad0e67a991d8477d8c01344b56e69c676ccb733f065b22436994b1253f86
  - if: target_platform == "win-arm64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-arm64.zip
      sha256: e4a7336010d58ff35b53d9dd5869095c56089c70913cf22508cf8183593e56b2

build:
  number: 1
  # Prefix replacement breaks in the binary embedded configurations.
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: linux
      then:
    # could be handled by https://github.com/conda-forge/linux-sysroot-feedstock/pull/87
        - git
        - if: build_platform != target_platform
          then: sysroot_${{ build_platform }} ${{ c_stdlib_version }}.*
    - if: unix
      then:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - python 3.8.*
        - ninja
        - pkg-config
    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv
    # need host builds of several lib dependencies
    # when cross-compiling
    - if: build_platform != target_platform
      then:
        - icu
        - openssl
        - zlib
  host:
    - if: not win
      then:
        - icu
        - libuv
        - openssl
        - zlib
  run_exports:
    - ${{ pin_subpackage('nodejs', upper_bound='x') }}

tests:
  - script:
      - node -h
      - node -v
      - npm version
      - npm install -h
      - npm config get prefix -g
      - if: not win
        then: test $(echo "console.log(1 + 3)" | node) == 4
      - if: osx
        then: test -f $PREFIX/lib/libnode.${{ NODE_MODULE_VERSION }}.dylib
      - if: linux
        then: test -f $PREFIX/lib/libnode.so.${{ NODE_MODULE_VERSION }}

about:
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications
  homepage: https://nodejs.org/
  repository: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
