schema_version: 1

context:
  version: "26.2.0"
  # NODE_MODULE_VERSION set in src/node_version.h
  NODE_MODULE_VERSION: 147

package:
  name: nodejs
  version: ${{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  - if: unix
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}.tar.gz
      sha256: 37032a75a677f063dbe22f0cc72249a3a2faff2ce71056b63771d6967bd63384
      patches:
        - patches/0001-stop-removing-librt.patch
        - patches/0002-include-obj-name-in-shared-intermediate.patch
        - patches/0003-Forward-ceilf-floorf.patch
        - patches/0004-Support-System-abseil-cpp.patch
  - if: target_platform == "win-64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-x64.zip
      sha256: 371071a4f7e2c8a5dd280730049c685911feecc59f50ebc488d675dc1087c69c
  - if: target_platform == "win-arm64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-arm64.zip
      sha256: 131efa8bd858f8ad000a1a0436d8bb1320c638291c779a921fb20e5702a1cc0a

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: linux
      then:
        - git
    - if: unix
      then:
        - ${{ stdlib('c') }}
        # Rust is required for Temporal only, see the comment in the test section.
        # - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        # c.f. https://github.com/nodejs/node/blob/v24.3.0/pyproject.toml#L10
        - python 3.13.*
        - ninja
        - pkg-config
        - sed
    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv
    # need host builds of several lib dependencies
    # when cross-compiling
    - if: build_platform != target_platform
      then:
        - libabseil
        - brotli
        - c-ares
        - icu
        - libnghttp2
        - libsqlite
        - libuv
        - openssl
        - zlib
        - zstd
  host:
    - if: not win
      then:
        - libabseil
        - brotli
        - c-ares
        - icu
        - libnghttp2
        - libsqlite
        - libuv
        - openssl
        - zlib
        - zstd
  run_exports:
    - ${{ pin_subpackage('nodejs', upper_bound='x') }}

tests:
  - script:
      - node -h
      - node -v
      - npm version
      - npm install -h
      - npm config get prefix -g
      - if: not win
        then:
          - test $(echo "console.log(1 + 3)" | node) == 4
          # Temporal support requires rust, thus make sure the toolchain gets picked up.
          # This currently disabled as this doesn't work together with a shared ICU, see also
          #   - https://github.com/nodejs/node/issues/62676
          #   - https://github.com/Homebrew/homebrew-core/pull/281707
          # - test $(node -e 'console.log(typeof Temporal)') == object || (echo "Temporal support not built"; exit 1)
      - if: osx
        then: test -f $PREFIX/lib/libnode.${{ NODE_MODULE_VERSION }}.dylib
      - if: linux
        then: test -f $PREFIX/lib/libnode.so.${{ NODE_MODULE_VERSION }}

about:
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications
  homepage: https://nodejs.org/
  repository: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
    - ytausch
