schema_version: 1

context:
  version: 22.21.1
  # NODE_MODULE_VERSION set in src/node_version.h
  NODE_MODULE_VERSION: 127

package:
  name: nodejs
  version: ${{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  - if: unix
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}.tar.gz
      sha256: 5407ff154708e3dd6c9eb40f787b79afc5db8b2461e4ae92ee54605515bba0f1
      patches:
        - patches/0001-stop-removing-librt.patch
        - patches/0002-include-obj-name-in-shared-intermediate.patch
        - patches/0003-Forward-ceilf-floorf.patch
  - if: target_platform == "win-64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-x64.zip
      sha256: 3c624e9fbe07e3217552ec52a0f84e2bdc2e6ffa7348f3fdfb9fbf8f42e23fcf
  - if: target_platform == "win-arm64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-arm64.zip
      sha256: b9d7faacd0b540b8b46640dbc8f56f4205ff63b79dec700d4f03d36591b0318f

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: linux
      then: git
    # could be handled by https://github.com/conda-forge/linux-sysroot-feedstock/pull/87
    - if: linux and build_platform != target_platform
      then: sysroot_${{ build_platform }} ${{ c_stdlib_version }}.*
    - if: unix
      then: 
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - python 3.8.*
        - ninja
        - pkg-config
    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv
    # need host builds of several lib dependencies
    # when cross-compiling
    - if: build_platform != target_platform
      then:
        - icu
        - openssl
        - zlib
  host:
    - if: not win
      then:
        - icu
        - libuv
        - openssl
        - zlib
  run_exports:
    - ${{ pin_subpackage('nodejs', upper_bound='x') }}

tests:
  - script:
      - node -h
      - node -v
      - npm version
      - npm install -h
      - npm config get prefix -g
      - if: not win
        then: test $(echo "console.log(1 + 3)" | node) == 4
      - if: osx
        then: test -f $PREFIX/lib/libnode.${{ NODE_MODULE_VERSION }}.dylib
      - if: linux
        then: test -f $PREFIX/lib/libnode.so.${{ NODE_MODULE_VERSION }}

about:
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications
  homepage: https://nodejs.org/
  repository: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
