schema_version: 1

context:
  version: "25.3.0"
  # NODE_MODULE_VERSION set in src/node_version.h
  NODE_MODULE_VERSION: 141

package:
  name: nodejs
  version: ${{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  - if: unix
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}.tar.gz
      sha256: 36cf586c51f20832ad27790f278f89f98a8dd957c4d6593d4f34e492249b3352
      patches:
        - patches/0001-stop-removing-librt.patch
        - patches/0002-include-obj-name-in-shared-intermediate.patch
        - patches/0003-Forward-ceilf-floorf.patch
        - patches/0004-Support-System-abseil-cpp.patch
  - if: target_platform == "win-64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-x64.zip
      sha256: 3c138ba2cd835b1af70ae2813422f544b2e786bdff8c0885ffb89fb7d407148e
  - if: target_platform == "win-arm64"
    then:
      url: https://nodejs.org/dist/v${{ version }}/node-v${{ version }}-win-arm64.zip
      sha256: ef217b4313cc6e9bd34a599e4d90f2e40a7ca5c30ae5a3098b32054b1c0d1727

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: linux
      then:
        - git
    - if: unix
      then:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        # c.f. https://github.com/nodejs/node/blob/v24.3.0/pyproject.toml#L10
        - python 3.9.*
        - ninja
        - pkg-config
        - sed
    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv
    # need host builds of several lib dependencies
    # when cross-compiling
    - if: build_platform != target_platform
      then:
        - libabseil
        - brotli
        - c-ares
        - icu
        - libnghttp2
        - libsqlite
        - libuv
        - openssl
        - zlib
        - zstd
  host:
    - if: not win
      then:
        - libabseil
        - brotli
        - c-ares
        - icu
        - libnghttp2
        - libsqlite
        - libuv
        - openssl
        - zlib
        - zstd
  run_exports:
    - ${{ pin_subpackage('nodejs', upper_bound='x') }}

tests:
  - script:
      - node -h
      - node -v
      - npm version
      - npm install -h
      - npm config get prefix -g
      - if: not win
        then: test $(echo "console.log(1 + 3)" | node) == 4
      - if: osx
        then: test -f $PREFIX/lib/libnode.${{ NODE_MODULE_VERSION }}.dylib
      - if: linux
        then: test -f $PREFIX/lib/libnode.so.${{ NODE_MODULE_VERSION }}

about:
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications
  homepage: https://nodejs.org/
  repository: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
    - ytausch
