bot:
  abi_migration_branches:
  - 18.x
  - 20.x
  - 22.x
  automerge: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
linter:
  skip:
  - lint_stdlib
provider:
  linux_64: github_actions
  osx_arm64: github_actions
test: native_and_emulated
