build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: default
conda_forge_output_validation: true
os_version:
  linux_64: cos7
test_on_native_only: true
bot:
  abi_migration_branches:
    - "12.x"
    - "14.x"
