appveyor: {image: Visual Studio 2017}
bot:
  abi_migration_branches: [12.x, 14.x]
build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: default}
test_on_native_only: true
