bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
test: native_and_emulated
conda_install_tool: pixi
conda_build_tool: rattler-build
