travis:
  secure:
    BINSTAR_TOKEN: ksVQFObr+hzndGfa5iSoLpqX6eXu5zsrerlIT8xQn9h4++930q7z7EIg7cbfWIBbKfVf5gJJ9g14RdZ72QcJFxzIlovoDVmg05gkUTEnRqVt3Hc7eaI2LJhI3aDh/t7CYrindkG5gNweFTSH3kgfOqWSBUTuzo6aoWPI3Lr4Bzv0VUDAjXj+YvHlT8LLhknExkZoOCez3vN1m++sFZOSiB/6nwnbxWgLrz3i7Dx3EDav4QnBsnp1B6V3QZqgkaGHoRW/UxjysTtG8+CB0jMVsjjT/Y1ZvZVNXdH1zgOl94a/MvAq7WY8C2irLbDknc0Fy/5aEPJBCi6PSHaJZ1FRVzCaAt5Mm/inDUyyt6hix9jpM91eoGYNtdy1O2n+uE+R6RoAZkeguENu7dsl34vML8X+x0y+4HiVbVqVa3J5jSsHw9dTVh0zZwMXAYvkfh30nL0kmW6A5wbH5YZe8If7Y80ZJ5vt2BUMurJtdaVhxcXU4xVlXuTlVamGwLFssUXZ1wkUzPyFJRFBfy/WoMCgNjstaPffe2SrwyQz/PrsvSJEnCPJiDECyVdk5RmMp4wOYek6K9NhZ3L0GxUXOCkbgJw/sPDef9Os0VOomtiW/BukfTNZFd2B6tXjThp1wA9lJsuDfRgQnwxM76UaVFCtx+SKojGfiA+JzxIRQHABMJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
