appveyor:
  image: Visual Studio 2017
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: default
conda_forge_output_validation: true
bot:
  abi_migration_branches:
    - "12.x"
    - "14.x"
