bot:
  abi_migration_branches:
  - 16.x
  - 18.x
  - 20.x
  automerge: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: github_actions
test: native_and_emulated
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
