appveyor:
  image: Visual Studio 2017
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: default}
travis:
  secure: {BINSTAR_TOKEN: JZwVDH5KwSyByzTRGbXzL6VEXx5Bsa942Rr0RHjvQ2kDhpxWx+g3uM+Z+46pZb162AbFX+fH28zZwMtLuIMhcBVOac+HT+1nJ90sXF4/h/J59OBshhThiwVx9nKQJ4/S5OlpM/UzTZfxEAOHLCpN8KVSGhdcj51UW2pNFcWFCOYM4xwXEwl1SZBrBZ6nl2nVIS33iF+lfcWv8g5ew2srtQY0N3+LL58sU2MPf/SBQiE72zUc8W9dzn3iJwA9Zn8w1PBIZWMXFK1Z+mJJl83rQwJ04aSSEqZsuPcs0vOTodr2CN7lM6Jx4ffI5s4qbsA2HPe5XrTZyVyQkEKzU5kehgMmUKQK5xHsE1ePMoR7oRINLLpDWVK8Z9rpjl7eJsb9XOtCQY8fEN64T7yybOKXEGUcOdcQuOh65ybS5HF1tiKwe9R2ULiqe9T/W8eNkq+B43yk7k7zOalc3PP3ZDWxrvZ6qHiugxVQ4rsTomBCAlpXJ2aw+uVafc/fSQgyqLzrstUjrLwmYK3nWCxB3O3iPArBY7cYzM/JJNguqCGYrF13LBZCnU5BggwVcg3grrLqzuraKlqGnLT/Uw8vBV03Gge4OzM8xTb03WCS46xOGYZI3QBG/lIvUtA/Wk5A2BmpaESQa2vfOYvvEudnzl22Oufu22QUCi1DyG1l8jf3s6A=}
